name: personal_expense_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  #webview
  webview_flutter: ^4.8.0 

  #state management
  provider: ^6.1.2

  #local storage
  hive_flutter: ^1.1.0

  #month picker
  month_picker_dialog: ^6.5.0

  #local notifications
  flutter_local_notifications: ^17.2.1+2

  #internationalization
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2

  #timezone
  timezone: ^0.9.4

  #slide
  flutter_slidable: ^3.1.1

  #service locator
  get_it: ^7.7.0
  permission_handler: ^11.3.1

  #app info
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  test: ^1.25.5

  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

  #launcher icon
  flutter_launcher_icons: ^0.13.1

  # splash screen
  flutter_native_splash: ^2.4.4

flutter_launcher_icons:
  android: true 
  remove_alpha_ios: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/app_icon.png"
  android: true
  ios: true
  
  android_12:
    color: "#FFFFFF"
    image: "assets/images/app_icon.png"

#flutter assets
flutter:
  uses-material-design: true

  assets:
    - assets/images/

#hive configuration
hive:
  boxNames:
    - expenses